#!/bin/bash
set -eo pipefail
shopt -s nullglob

#if [ ! -z "$HOSTNAME" ]; then
  #sed -i "s/quickstart.cloudera/${HOSTNAME}/" /etc/hadoop/conf/core-site.xml
  #sed -i "s/quickstart.cloudera/${HOSTNAME}/" /etc/hue/conf/hue.ini
#fi

pip3 install -r /workspace/requirements.txt

echo
echo 'Config process done. Ready for startup.'
echo 

exec "$@"
