apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: higgs-redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        app: higgs-redis
    spec:
      volumes:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: higgs-redis-svc
  labels:
    app: higgs-redis 
spec:
  ports:
  - port: 6379 
    name: redis
  selector:
    app: higgs-redis
