#!/bin/bash

################################
## PART: install the packages
##
pkgutils=(apt-utils
          debconf-utils
          ca-certificates
          lsb-release
)

################################
## PART: install the packages
##
pkgs=(curl
      jq
      less
      python-pip
      python-virtualenv
      python3-pip
      python3-virtualenv
      sudo
      tree
      vim
      wget
)

export DEBIAN_FRONTEND=noninteractive
apt-get -qqy update
apt-get -qqy install ${pkgutils[@]}
apt-get -qqy install ${pkgs[@]}
apt-get -qqy clean
rm -rf /var/lib/apt/lists/*
