#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

###################################

## gcloud sdk

###################################

pip3 install \
  pyasn1 \
  pyasn1-modules \
  google-auth-oauthlib \
  google-cloud

export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

apt-get -qqy update
apt-get install -qqy \
  google-cloud-sdk \
  kubectl
